# Generated by Django 3.0.6 on 2020-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('humedad', models.CharField(max_length=10)),
            ],
        ),
    ]
