# Generated by Django 3.0.6 on 2020-07-09 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_awa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
