# Generated by Django 3.0.6 on 2020-07-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_awa', '0003_variables_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='awa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_y_hora', models.DateField()),
                ('Temperatura', models.CharField(max_length=10)),
                ('Humedad', models.CharField(max_length=10)),
                ('OD', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='variables',
            name='hora',
        ),
        migrations.AlterField(
            model_name='variables',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
