# Generated by Django 3.0.6 on 2020-07-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_awa', '0004_auto_20200709_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awa',
            name='Fecha_y_hora',
            field=models.DateTimeField(),
        ),
    ]
